#!/bin/bash

source ~/.config/lpit/lpitPushChanges.bash

if [ $# -ne 0 ] ; then
  remoteHost=$1
fi

echo $remoteHost
echo $remoteUser
echo $remoteHtmlDir

$sshKeyCmd

rsync -av \
  ~/.cache/lpit/webSite/ \
  $remoteUser@$remoteHost:$remoteHtmlDir

