#!/bin/sh

# This shell script watches our use of TailWindCSS and updates our custom
# CSS files

exec tailwindcss \
  --watch \
  --input lpitPublisher/css/main.css \
  --output ~/.cache/lpitPublisher/webSite/css/main.css

